### ISSUE TITLE
Sim Queue

### ISSUE THREAD

**Issue by ragnarger** [Twintop/beotorch-issues#16]
If i have a Simulation without Scaling Factors running (1 Slot) i cannot queue another Simulation with Scaling Factors "on" (5 Slots). It always says, i have not enough free slots.

**Comment by Twintop** [comment]
Can you tell me the Region+Server+Character+Spec you used? How many bosses were you trying to sim with? Thanks!

**Comment by Twintop** [comment]
Haven't been able to reproduce this. With the changes to the queue cost with the introduction of talent comparison sims, if this was a problem it is probably fixed now. Closing.
