### ISSUE TITLE
Highest DPS Talentset is incorrect

### ISSUE THREAD

**Issue by ThePants999** [Twintop/beotorch-issues#18]
On the "Your Simulations" page, for a simulation that included multiple talentsets, the "Result" column shows the "Highest DPS Talentset". However, it appears to be showing the DPS from the first talentset in the simulation, not the highest DPS one. Example: simulation d8b946f5-4ed4-11e6-bd4d-008cfa070490 is showing has 45252 DPS, when it includes one talentset at 45252 and one at 70898.

**Comment by Twintop** [comment]
Thanks for the bug report and providing example reports! I'll have a look and see why it isn't returning the max DPS value. Cheers!

**Comment by Twintop** [comment]
Just pushed some SPROC changes live that should fix this. Thanks again!
