### ISSUE TITLE
Constant Logging Out

### ISSUE THREAD

**Issue by dj-riff** [Twintop/beotorch-issues#21]
For some reason when alt tabbing or just being in active for 10-300 seconds (i timed it) it'll randomly log me out of the site. This happens frequently when queuing up a sim and then going afk for a little bit, then having to log back in.

I'm using Google Chrome, most up to date version.

**Comment by Twintop** [comment]
This has been an issue with PHP's `session_set_cookie_params()` function for a while. I think I found a workaround but I need to let the change soak on my dev environment for a bit to verify.

**Comment by Twintop** [comment]
Attempted fix didn't work, still looking at other options. No ETA.

**Comment by Twintop** [comment]
Took a different approach. Letting it soak again on my dev environment. Fingers crossed, etc.

**Comment by Twintop** [comment]
Looks like the fix actually took. \o/ Hopefully I'll push a new version of the site this weekend that includes it.
