### ISSUE TITLE
Url 404 code

### ISSUE THREAD

**Issue by meltinglava** [Twintop/beotorch-issues#5]
Hello

http://www.beotorch.com/warehouse/8e84e5ca-da80-11e5-86e3-008cfa070490.html
I found a 404 bug with pressing the URL at: 8e84e5ca-da80-11e5-86e3-008cfa070490.json

**Comment by Twintop** [comment]
Thanks for the heads up!

This is because I'm using a local copy of your character's armory JSON when running simulations. I'll look in to redirecting this link to some script that will give the JSON used when clicked, but it is a low priority right now.
