### ISSUE TITLE
Non-active spec

### ISSUE THREAD

**Issue by ale-devl** [Twintop/beotorch-issues#7]
Maybe I'm blind, in that case I'm sorry.
But an option that allows the use of our inactive spec for simulations would be highly appreciated!
I often use your service from the office where I can't access my character to switch specs but would still like to compare them.
Anyways, thanks for this truly amazing service :heart:

**Comment by Twintop** [comment]
This feature is definitely on my list of priorities (along with choosing to do a DPS or Tank sim, if you have an appropriate spec). It requires some not-insignificant changes to how queueing up a new simulation works, though. If I had to give a time estimate, probably a few weeks from now. Thanks!

**Comment by ale-devl** [comment]
Awesome, I'll keep an eye out for it :)
